name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: gabriel23i
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:

- nome: Cache
  usa: actions/cache@v2.1.7
  com:
    # Uma lista de arquivos, diretórios e padrões curinga para armazenar em cache e restaurar
    caminho: 
    # Uma chave explícita para restaurar e salvar o cache
    chave: 
    # Uma lista ordenada de chaves a serem usadas para restaurar o cache se nenhum acerto de cache ocorreu para a chave
    chaves de restauração: # opcional
    # O tamanho do bloco usado para dividir arquivos grandes durante o upload, em bytes
    upload-chunk-size: # opcional
